# @format

name: justclap
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_svg: ^1.0.3
  flutter_fadein: ^2.0.0
  velocity_x: ^3.3.0
  retrofit: ^3.0.1
  get_storage: ^2.0.3
  intl: ^0.17.0
  rating_dialog: ^2.0.4
  intl_phone_number_input: ^0.7.0+2
  url_launcher: ^6.0.20
  file_picker: ^4.5.1
  pull_to_refresh: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner: any
  retrofit_generator: 4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icon.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/provider/
    - assets/user/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Regular.ttf
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
